import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/sections/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Palette (raw)
        palette: {
          "dark-900": "#1E212B",
          "dark-800": "#2A2F3A",
          "dark-700": "#353A47",
          "cream-50": "#F7F5F0",
          "cream-25": "#FAFAF8",
          "gold-500": "#F1A21B",
          "gold-400": "#F1CA24",
          "gold-600": "#D68E16",
          "cyan-500": "#00C2D1",
          "cyan-700": "#0097A3",
          "cyan-100": "#E0F7F9",
          "red-500": "#E11D48",
          "red-600": "#B91C3C",
          ink: "#2A2F3A",
          "ink-light": "#6E7683",
          white: "#FFFFFF",
          "dark-950": "#12141B",
          // Sunset gradient stops
          "sunset-gold": "#F1A21B",
          "sunset-amber": "#D68E16",
          "sunset-rose": "#E11D48",
          "sunset-dusk": "#6B1E36",
          "sunset-night": "#2A2F3A",
          "sunset-deep": "#12141B",
        },
        // Intent
        bg: "var(--color-bg)",
        card: "var(--color-card)",
        input: "var(--color-input)",
        dark: "var(--color-dark)",
        "dark-muted": "var(--color-dark-muted)",
        body: "var(--color-body)",
        muted: "var(--color-muted)",
        heading: "var(--color-heading)",
        "on-dark": "var(--color-on-dark)",
        "on-dark-muted": "var(--color-on-dark-muted)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "on-accent": "var(--color-on-accent)",
        alert: "var(--color-alert)",
        "alert-hover": "var(--color-alert-hover)",
        "on-alert": "var(--color-on-alert)",
        active: "var(--color-active)",
        success: "var(--color-success)",
        "on-success": "var(--color-on-success)",
        callout: "var(--color-callout)",
        "on-callout": "var(--color-on-callout)",
        error: "var(--color-error)",
        "focus-ring": "var(--color-focus-ring)",
        divider: "var(--color-divider)",
        border: "var(--color-border)",
        "border-subtle": "var(--color-border-subtle)",
        "border-soft": "var(--color-border-soft)",
        "dark-subtle": "var(--color-dark-subtle)",
        "dark-soft": "var(--color-dark-soft)",
        "accent-subtle": "var(--color-accent-subtle)",
        "error-subtle": "var(--color-error-subtle)",
        "success-subtle": "var(--color-success-subtle)",
        "callout-subtle": "var(--color-callout-subtle)",
        "on-dark-accent": "var(--color-on-dark-accent)",
        "on-dark-accent-hover": "var(--color-on-dark-accent-hover)",
        "on-dark-subtle": "var(--color-on-dark-subtle)",
        "on-dark-soft": "var(--color-on-dark-soft)",
        // Immersive (cinematic dark / photographic)
        "immersive-bg": "var(--color-immersive-bg)",
        "immersive-bg-deep": "var(--color-immersive-bg-deep)",
        "immersive-bg-night": "var(--color-immersive-bg-night)",
        "on-immersive": "var(--color-on-immersive)",
        "on-immersive-muted": "var(--color-on-immersive-muted)",
        "immersive-accent": "var(--color-immersive-accent)",
        "immersive-accent-hover": "var(--color-immersive-accent-hover)",
        "immersive-cool": "var(--color-immersive-cool)",
        "immersive-subtle": "var(--color-immersive-subtle)",
        "cyan-subtle": "var(--color-cyan-subtle)",
        // Header
        "header-bg": "var(--color-header-bg)",
        "header-hover-border": "var(--color-header-hover-border)",
        "header-cheatline": "var(--color-header-cheatline)",
        "header-button-1-bg": "var(--color-header-button-1-bg)",
        "header-button-1-text": "var(--color-header-button-1-text)",
        "header-button-2-bg": "var(--color-header-button-2-bg)",
        "header-button-2-text": "var(--color-header-button-2-text)",
        "header-button-3-bg": "var(--color-header-button-3-bg)",
        "header-button-3-text": "var(--color-header-button-3-text)",
        "header-button-4-bg": "var(--color-header-button-4-bg)",
        "header-button-4-text": "var(--color-header-button-4-text)",
        "header-button-5-bg": "var(--color-header-button-5-bg)",
        "header-button-5-text": "var(--color-header-button-5-text)",
        "header-cta-bg": "var(--color-header-cta-bg)",
        "header-cta-text": "var(--color-header-cta-text)",
        "header-cta-hover": "var(--color-header-cta-hover)",
        // Footer
        "footer-bg": "var(--color-footer-bg)",
        "footer-text": "var(--color-footer-text)",
        "footer-muted": "var(--color-footer-muted)",
        "footer-link": "var(--color-footer-link)",
        "footer-link-hover": "var(--color-footer-link-hover)",
        // Legacy aliases (deprecated)
        navy: {
          900: "var(--color-navy-900)",
          800: "var(--color-navy-800)",
        },
        sand: {
          50: "var(--color-sand-50)",
        },
        gold: {
          500: "var(--color-gold-500)",
          400: "var(--color-gold-400)",
        },
        orange: "var(--color-orange)",
        rust: "var(--color-rust)",
        ink: {
          DEFAULT: "var(--color-ink)",
          light: "var(--color-ink-light)",
        },
        teal: {
          DEFAULT: "var(--color-teal)",
          100: "var(--color-teal-100)",
          700: "var(--palette-cyan-700)",
        },
      },
      fontFamily: {
        heading: ["Nunito Sans", "system-ui", "sans-serif"],
        body: ["Poppins", "system-ui", "sans-serif"],
        mono: ["IBM Plex Mono", "Courier New", "monospace"],
        display: ["Spectral", "Georgia", "serif"],
      },
      screens: {
        xs: "375px",
      },
    },
  },
  plugins: [],
};

export default config;